export const nombresLegibles: Record<string, string> = {
  arboles: 'Arboles',
  arbustos: 'Arbustos',
  aromaticas: 'Aromaticas',
  bonsai: 'Bonsai',
  compost: 'Compost',
  coniferas: 'Coniferas',
  budista: 'Estrtuctura Budista',
  hinduista: 'Estructura Hinduista',
  fertilizantes: 'Fertilizantes',
  carozo: 'Frutales de Carozo',
  pepita: 'Frutales de pepita',
  secos: 'Frutales Secos',
  gramineas: 'Gramineas',
  herbicidas: 'Herbicidas',
  insecticidas: 'Insecticidas',
  jardin: 'Juegos de Jardin',
  macetas: 'Macetas',
  plantasnativas: 'Plantas Nativas',
  plantines: 'Plantines',
  rosales: 'Rosales',
  sustrato: 'Sustrato',
  
};